### PR TITLE
Indexing example

### PR DESCRIPTION
**Pull request by hdoupe**
This PR adds a Parameter Indexing example to the repo. An `IndexedParameters` class is added at `paramtools/examples/taxparams/parameters.py`. I did a write up on this example in a notebook that you can view here: https://github.com/PSLmodels/ParamTools/blob/index-ex/paramtools/examples/taxparams/IndexedParametersEx.ipynb. You can also run the notebook locally. 

I based the example on Tax-Calculator's indexing approach. I also compared the indexed values with Tax-Calculator's to make sure that they were correct. I'm interested to hear what people think about this example.

This is related to #34.

cc @martinholmer

### CODE REVIEW

**Comment by hdoupe** [comment]
Some questions that I'm considering for this post are:

- Is the intermediate example under ["Indexed Parameter Intuition"][1] helpful?
- Would it be helpful to annotate the [`IndexedParameter` code][2]? I wrote a version where I did this, but it was hard to read. In the end, I decided that it would be better to discuss what's going on in general and leave examining the code to people that are interested in knowing exactly how it works.

I'd appreciate any feedback on these questions in addition to people's general take on the post.

[1]: https://nbviewer.jupyter.org/github/PSLmodels/ParamTools/blob/index-ex/paramtools/examples/taxparams/IndexedParametersEx.ipynb#Indexed-Parameters-Intuition

[2]: https://nbviewer.jupyter.org/github/PSLmodels/ParamTools/blob/index-ex/paramtools/examples/taxparams/IndexedParametersEx.ipynb#IndexedParameters-Class

**Comment by andersonfrailey** [comment]
Sorry for taking so long to get you some feedback. Overall this was very good. I just have a few suggestions.

First, I would add a link to Tax-Calculator so the reader can check it out and learn a little more if they'd like to gain some additional context. In that vein, it'd be helpful if you explained in a little more detail what indexed parameters mean in this case and what TaxParams is supposed to do. A quick overview of what `schema.json` and `defaults.json` contain would be helpful, for me at least.

Second, now that ParamTools is on Conda, I'd update the installation instructions to reflect that. Unless there's a reason to install a development version in which case ignore me.

Third, the TaxParams class is defined three times. Two duplicates and once with a bunch of new stuff. More on what is being added/changed with each new definition would be helpful. It could be done as markdown text or just more comments in the code, which ever you find easier/more informative.

Overall this is a really informative post. It would be complemented nicely with a more general introduction to ParamTools post as well in my opinion.

**Comment by hdoupe** [comment]
Thanks for your feedback @andersonfrailey. I'll make some changes this week and ping you when they are up!

**Comment by hdoupe** [comment]
Closing #39 in favor of #65.

**Pull request closed without merging**
